### ISSUE TITLE
Can not use parser with classes

### ISSUE THREAD

**Issue by roma86** [hodinkee/alexander#1]
Hello. Just try use swift 2 branch for project, that depend on realm, so i can not use `struct` with models.

Here model looks like:

``` swift
import RealmSwift
import Alexander

class NewsItem: Object, JSONDecodable {
    dynamic var sid = 0
    dynamic var title = ""

    required init( sid: Int, title: String ) {
        super.init()
        self.sid = sid
        self.title = title
    }

    required init() {
        super.init()
    }

    static func decode(JSON: Alexander.JSON) -> Self? {

        if
            let sid = JSON["id"]?.int,
            let title = JSON["title"]?.string {
                return NewsItem(sid: sid, title: title)
        }
        return nil
    }
}
```

I am still not familiar with swift, but looks similar to example code in readme. 

Therefore i have error 

![compiler error](https://api.monosnap.com/rpc/file/download?id=76dm4Rg2o2D8pWKFus5v1lhr5Vczde)

`Cannot convert return expression of type 'NewsItem' to expected return type 'Self'`

**Comment by calebd** [comment]
You can use Alexander with classes in Swift just fine.

The short version: Change `-> Self?` to `-> NewsItem?`, or make your class `final`.

The long version: Swift is telling you that you cannot promise that `decode` will in fact return a `Self`. A subclass of `NewsItem` that does not override `decode` will still return a plain `NewsItem` and not an instance of the receiving class. Structs and final classes can safely use `Self` because the compiler can guarantee the type of the object that is returned.
